In [7]:
import pandas as pd

In [8]:
#loading data from a csv file
ufo_data = pd.read_csv("http://bit.ly/uforeports")

In [10]:
ufo_data.head(3)

          City Colors Reported Shape Reported State             Time
0       Ithaca             NaN       TRIANGLE    NY   6/1/1930 22:00
1  Willingboro             NaN          OTHER    NJ  6/30/1930 20:00
2      Holyoke             NaN           OVAL    CO  2/15/1931 14:00

In [11]:
#reading a tsv file
chips_data = pd.read_table("http://bit.ly/chiporders")

In [13]:
#reading tsv files with read_csv,but by using the sep parameter
chips_data = pd.read_csv("http://bit.ly/chiporders",sep='\t')

In [14]:
"""display data we use head(n)function where
n - is yhe number or rows of the data
example:chips_data.head(5)
this means its only 5 rows which will be displayed,starting from 0.
"""
chips_data.head(5)

,order_id,quantity,item_name,choice_description,item_price
0,1,1,Chips and Fresh Tomato Salsa,NaN,$2.39
1,1,1,Izze,[Clementine],$3.39
2,1,1,Nantucket Nectar,[Apple],$3.39
3,1,1,Chips and Tomatillo-Green Chili Salsa,NaN,$2.39
4,2,2,Chicken Bowl,"[Tomatillo-Red Chili Salsa (Hot), [Black Beans...",$16.98

In [17]:
"""to display row of data from bottom of the table we use tail(n) function, where "n" is the
total number of the last row.Example: chips_data.tail(4)
"""
chips_data.tail(6)

,order_id,quantity,item_name,choice_description,item_price
4616,1832,1,Chips and Guacamole,NaN,$4.45
4617,1833,1,Steak Burrito,"[Fresh Tomato Salsa, [Rice, Black Beans, Sour ...",$11.75
4618,1833,1,Steak Burrito,"[Fresh Tomato Salsa, [Rice, Sour Cream, Cheese...",$11.75
4619,1834,1,Chicken Salad Bowl,"[Fresh Tomato Salsa, [Fajita Vegetables, Pinto...",$11.25
4620,1834,1,Chicken Salad Bowl,"[Fresh Tomato Salsa, [Fajita Vegetables, Lettu...",$8.75
4621,1834,1,Chicken Salad Bowl,"[Fresh Tomato Salsa, [Fajita Vegetables, Pinto...",$8.75

In [19]:
#Sample is used for exploring diverse parts of the database.
#Example: chips_data.sample(5)
chips_data.sample(4)

,order_id,quantity,item_name,choice_description,item_price
2380,947,2,Steak Burrito,"[Fresh Tomato Salsa (Mild), [Pinto Beans, Chee...",$17.98
135,60,2,Chicken Salad Bowl,"[Tomatillo Green Chili Salsa, [Sour Cream, Che...",$22.50
2310,926,1,Steak Burrito,"[Roasted Chili Corn Salsa, [Rice, Cheese, Sour...",$9.25
1430,579,1,Carnitas Bowl,"[[Tomatillo-Red Chili Salsa (Hot), Fresh Tomat...",$11.48

In [21]:
chips_data.shape

(4622, 5)

In [22]:
chips_data.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 4622 entries, 0 to 4621
Data columns (total 5 columns):
 #   Column              Non-Null Count  Dtype
---  ------              --------------  -----
 0   order_id            4622 non-null   int64
 1   quantity            4622 non-null   int64
 2   item_name           4622 non-null   object
 3   choice_description  3376 non-null   object
 4   item_price          4622 non-null   object
dtypes: int64(2), object(3)
memory usage: 180.7+ KB

In [23]:
chips_data.describe()

          order_id     quantity
count  4622.000000  4622.000000
mean    927.254868     1.075725
std     528.890796     0.410186
min       1.000000     1.000000
25%     477.250000     1.000000
50%     926.000000     1.000000
75%    1393.000000     1.000000
max    1834.000000    15.000000